### ISSUE TITLE
Create a view that makes the stream table more conveniently accessible

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#11]
For example:

The Hive table can be queried like this:
`SELECT stream.record.id id FROM (SELECT CONVERT_FROM(record, 'JSON') record FROM streams.appevent) stream LIMIT 1`

Defining a view can make it nicer to work with:
`CREATE OR REPLACE VIEW dfs.tmp.stream_appevent AS SELECT CONVERT_FROM(record, 'JSON') record FROM streams.appevent`

This can then be queried like:
`SELECT e.record.id id FROM dfs.tmp.stream_appevent e LIMIT 1`

**Comment by pmogren** [comment]
Dependent upon #10

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
