### ISSUE TITLE
Create a view that unions the stream table/view with the stream archive table

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#12]
Ideally with de-duplication of records that are both archived and still retained by the stream.

Is this going to be compatible with path-based partitioning of the archive table?

**Comment by pmogren** [comment]
May require upgrading Drill.
Maybe a CTE (WITH clause) can be used instead of UNION.

**Comment by pmogren** [comment]
Dependent upon #10

**Comment by pmogren** [comment]
The aforementioned Drill upgrade (to 1.1.0) was done.

**Comment by pmogren** [comment]
And so was the shared writable storage plugin (#10). This is unblocked.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
