### ISSUE TITLE
Enable better security of S3 credentials

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#15]
S3 credentials currently are exposed in the storage plugin configuration. Can that be secured? I think I saw some recent chatter about that in Drill world, so not yet by anything they offer - maybe put a web server in front of it?

Credentials could be put into files on the nodes, but then they are hard to change. Doesn't fit with our goal of allowing storage plugins to be reconfigured a running cluster.

Using EMRFS (#13) rather than Jets3t to access S3 might enable access based on IAM (EC2 Instance Roles).

Maybe it doesn't matter as long as we are requiring SSH port forwarding to access the Drill UI.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
