### ISSUE TITLE
Add test coverage for user storage configuration

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#17]
Provide a way for a user to verify that user-configured stream archives and streams can be correctly searched with Drill.

**Comment by pmogren** [comment]
This needs some thought before proceeding. Do we expect the user to provision the stream archives and streams? Do we expect the user to provide data in the stream archives and streams, or do we send test data? Do we expect the user to provide queries to execute? How long should queries take?

**Comment by pmogren** [comment]
Maybe this should be handled as a way to validate that an already-built cluster works as expected.

**Comment by pmogren** [comment]
Decided to make this dependent on #14 and leverage the new configuration files

**Comment by pmogren** [comment]
Depends on #39

**Comment by nelsonw2014** [comment]
Is expecting one record in each location an acceptable expectation?

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
