### ISSUE TITLE
Add project test coverage for storage configuration functionality

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#18]
Provide a way for a project developer to verify that a known valid configuration of stream archives and streams can be correctly searched with Drill.

**Comment by pmogren** [comment]
Depends on #17 and #5

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
