### ISSUE TITLE
Consider applying timeouts to tests

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#19]
When things like creating a cluster or querying Drill go bad, they sometimes never return, or not for an hour. We should probably make them time out, and ensure the cluster still gets cleaned up. On one hand, it's hard to guess how long things should take, especially if a user has a very different configuration than us. On the other hand, a newer user might not have any idea what is a sensible timeout, and if they kill it, they'll have to also remember to manually clean up.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
