### ISSUE TITLE
Define a wrapper record format

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#21]
Rather than archive Kinesis records as-is, it may be advantageous to wrap them in a container that could also contain metadata, e.g. timestamp, stream name, sequenceId, headers.

In issue #24 it was determined that the original record should not be the top-level object, but rather exist under the key 'record' to match the Hive column name, in order to let the same queries work on either an archive or a view over a stream.

Maybe the pristine original record should also be kept, encoded in a single value.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
