### ISSUE TITLE
Maybe create a custom Kinesis storage handler

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#22]
https://github.com/qubole/kinesis-storage-handler could be used as a base implementation; it appears to be extremely similar to the one provided by EMR.

Interesting customizations might include:
* Letting the termination timeout on no new data be sub-minute
* Terminating when the stream has been read up to the LATEST record available when the query started, rather than continuing to follow new data until a fixed execution timeout or number of iterations is reached
* Exposing the sequence number and other metadata on records, not just the payload
* Discards records not containing valid JSON, so they don't break Drill

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
