### ISSUE TITLE
Move query profile storage to shared writable location

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#27]
Currently it is stored per-node, so a Drill UI user can only see what happened to execute on the same node that service their request.

Depends on #10

**Comment by pmogren** [comment]
I tried putting this on HDFS, but it turns out to be really difficult to do with EMR. The Drill configuration has to be done on each node. 

'Bootstrap actions', which run on each node, run before HDFS is available. Drill fails to start when configured to log to HDFS and it's not available. 

'Steps' run after HDFS is available, but do not run on all nodes.

Starting HDFS early on the Master did not work, and was a flawed idea because the master is not meant to run DataNode, only NameNode. Since we have no control over the timing of when the various instances are provisioned and bootstrapped, we can't try to coordinate starting both a NameNode and a DataNode early on different instances. I'm not sure why this didn't even work in a single-node cluster, though; both NameNode and DataNode started, but got SIGTERM one second after starting, before they could be used.

**Comment by pmogren** [comment]
Maybe EMRFS is an option, though it doesn't seem appropriate.

Here is an example of detecting all nodes and using ssh to run a script on each:
http://earlh.com/blog/2013/05/02/modifying-the-number-of-mappers-or-reducers-on-a-running-emr-cluster/

**Comment by pmogren** [comment]
If we can switch to MapR, maprfs should work.

**Comment by pmogren** [comment]
NFS on the master node? Could be lost at any time unless we also create and mount an EBS volume for it. 
https://theredblacktree.wordpress.com/2013/05/23/how-to-setup-a-amazon-aws-ec2-nfs-share/

**Comment by pmogren** [comment]
What about shipping the logs off to an aggregator?

**Comment by pmogren** [comment]
GlusterFS etc?

**Comment by pmogren** [comment]
Drill docs suggest maprfs, maprdb, or hbase
 https://drill.apache.org/docs/persistent-configuration-storage/

**Comment by pmogren** [comment]
Amazon Elastic File System is only in preview, and that only in the Oregon region.

**Comment by pmogren** [comment]
Probably we should embrace the short-lived approach, as Drill does, and not worry about node loss. Maybe don't even worry about the cluster being scaled.

**Comment by pmogren** [comment]
I think something changed in how this is stored, in more recent versions of Drill

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
