### ISSUE TITLE
Support new EMR release

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#31]
https://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-release-components.html

Upside: contains Hive 1.0 which is what Drill 1.1 officially supports.

**Comment by pmogren** [comment]
http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-release-differences.html
Summary:
* Will need to specify ReleaseLabel rather than AmiVersion.
* Specification of installing Apps like Hive has changed, and Impala is no longer an option.
* Hive-Metastore maybe now has first-class support? Lack thereof was the only reason we have been installing Impala.
* Specification of Hadoop configuration parameters has changed.
* HDFS NameNode port (used in Drill configuration) changed from 9000 to 8020.
* Other ports that we currently forward over SSH have also changed.
* All apps don't run as user 'hadoop' now. Maybe we should create a 'drill' user.
* Binaries like 'hive' and their config files have moved. Maybe our Drill install should move too.
* Log files have moved.

**Comment by pmogren** [comment]
At this point it might be worth switching to MapR instead. I started one up and it still has all of the special EMR jars for connecting to Kinesis, EMRFS, DynamoDB etc.  In MapR 4.0.2 M3, Drill is pre-installed with version 1.0.0, and Hive version 0.13.1-amzn-1. Have not investigated how to upgrade - supposedly the install was going to get the latest version.  MapR 5 is not yet available, at least through the AWS EMR console, but I expect it will use Drill 1.1 and Hive 1.0.  Drill is installed to /opt/drill.  Zookeeper 3.4.5 is already installed. Java 1.7.0_71, Python 2.6.9 (default) and 2.7.8, Scala 2.11.1, several versions of Ruby.

**Comment by pmogren** [comment]
Why should we be interested in MapR?
* They are the main drivers of Drill development, so MapR is the best supported platform for Drill. It is the distro used for "sandbox" and "test drive" trials of Drill.
* maprfs is more useful than HDFS
* It's a popular hadoop distro; most hadoop users run a commercially packaged distro, not raw apache
* It can more readily grow with us as we care more about Hadoop, which may also be more important to other more Hadoop-savvy users of watershed: support contracts, high availability, security, etc.

**Comment by pmogren** [comment]
"MapR comes in three editions.

M3 is free and gives you all the performance and scalability, but limits you to a single NFS server and no mirrors, snapshots, volume locality or HBase compatible API (you can run HBase itself, of course). HA is also degraded in M3 so that it takes an hour to fail over certain functions.

M5 costs money after the free trial period and gives you snapshots, mirrors, the ability to force some data to different topologies and unlimited NFS servers.

M7 also costs money and adds the HBase API to all that M5 can do."

Source: decent answers to a bad question: http://stackoverflow.com/questions/17145031/is-it-possible-to-combine-mapr-to-pure-apache-hadoop

**Comment by pmogren** [comment]
Let's go to EMR 4, not MapR

**Comment by pmogren** [comment]
Now a high priority because "Amazon EMR now requires you to use version 4.2.0 in order to utilize private subnets." according to issue #63.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
