### ISSUE TITLE
Prevent timeout of port forwarding

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#32]
There is an SSH client option to heartbeat the connection to discourage the server from closing the connection due to inactivity. We should enable this, at least optionally.

**Comment by nelsonw2014** [comment]
I think that sshtunnel automatically handles connection inactivity issues. I'll test this today.

**Comment by pmogren** [comment]
It timed out on me yesterday.

**Comment by nelsonw2014** [comment]
Which port/application so I can replicate?

**Comment by pmogren** [comment]
I was using 8047/drill-ui occasionally.  When I went too long without using it, the SSH tunnel died.

**Comment by pmogren** [comment]
Did not see an option available to set. Issue filed with sshtunnel dependency: https://github.com/pahaz/sshtunnel/issues/29

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
