### ISSUE TITLE
Wait command/option should wait for Waiting status, not Running, when we submit steps

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#39]
..since the requested functionality is not usable until all of the steps are complete.

I don't know if there is currently a wait option on the new configure-archives and configure-streams options, but there should be - check that and add if missing.

**Comment by nelsonw2014** [comment]
The waiter will not work for configure-archives and configure-streams because it's only designed to wait during initial bootstrapping. The 'steps' are considered normally running.

**Comment by nelsonw2014** [comment]
Two options exist.
1. Make all required functionality happen in steps instead of manual execution
2. Bootstrap the configure archives and streams as they were previously

**Comment by pmogren** [comment]
To clarify:
* The goal here is for the user to get feedback when storage configuration is complete because that's when the system actually becomes testable and useful.
* Storage configuration should not be bootstrap actions, because reconfiguration should not require rebuilding the cluster.
* Boto3 does not provide a Waiter object for step completion, nor for cluster status subsequent to the completion of bootstrap actions. However, we could write code to poll the status of the steps we submitted (or maybe cluster status if we can assume nothing else is submitting steps).

**Comment by nelsonw2014** [comment]
I created the waiting function for steps, but do you want to make the wait-for-cluster command to leverage it? The issue is that steps take a lot less time than standing up a cluster. The function I made is designed to check more often than the emr waiter and retry for a shorter period.

**Comment by pmogren** [comment]
I assume that since steps can be submitted at launch time, steps can also be submitted at any time during launch, so there is not much reason to ever wait for the cluster to be RUNNING.  Besides, there are always initial steps (e.g. Hive installation) to wait for before the cluster is actually useful. So yes, I think cluster launch should wait on step completion.  If there is an issue with timing expectations, I suggest waiting for cluster RUNNING and then waiting for step completion.
