### ISSUE TITLE
Add test harness to establish a dummy config for testing the project itself

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#5]

**Comment by nelsonw2014** [comment]
What data would you like included in this harness? Just the configuration? Private key generation as well? Should it define roles and streams and buckets automatically?

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
