### ISSUE TITLE
Create views to unwrap JSON to make it searchable

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#51]
For example, a view could encapsulate the need for the CTE (WITH clause) in the query below:

```WITH unwrapped(metaData, rawData, jsonData) AS ( SELECT metaData, rawData, CONVERT_FROM(rawData, 'JSON') AS jsonData FROM bucket.workspace.table ) 
SELECT u.metaData, u.rawData, u.jsonData.something, u.jsonData.nested.thing FROM unwrapped u WHERE u.jsonData.nested.thing = 1```

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
