### ISSUE TITLE
Install Broken - Doesn't include pump because it's outside of the package

### ISSUE THREAD

**Issue by nelsonw2014** [commercehub-oss/watershed#62]
When installing rather than setting up for development, watershed doesn't include the resources required for pump (the source of pump) and will fail to upload the files when asked. This can be remedied by relocating the files for pump inside the resources folder in watershed.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
