### ISSUE TITLE
Stream archival

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#7]
We could:
* implement something
* recommend another OSS project
* just provide guidance

**Comment by pmogren** [comment]
Considerations:
Data format, e.g. JSON
Record format, e.g. Stripped of newlines, one record per line
File size
Compression
Exclusion of records that are invalid in the expected format, so as to not break Drill; maybe save them off to the side
Helping Drill to understand the schema, e.g. by declaring the superset of all schema collected into a file,  declaring the important schema that is known in advance, or limiting files to 10000 records so Drill will analyze them all
Writing  known schema in a more structured format, with the full original record embedded in a field or stored elsewhere

**Comment by aheiss1** [comment]
Providing https://github.com/awslabs/amazon-kinesis-connectors ITransformer and IEmtter implementations could be helpful, but would place burden on users to integrate them into their systems.  Understandably, not an ideal OOTB solution.   At a minimum, they could help describe the expected storage format.

**Comment by pmogren** [comment]
Refocus on supporting Kinesis Firehose.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
