### ISSUE TITLE
Clean up AWS SDK import into Drill classpath (setup_drill_lib_aws)

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#8]
The setup_drill_lib_aws script currently imports into Drill's classpath:
* enough of the emr-* jars which are placed automatically on each node
* the entire aws-java-sdk, but very few of its dependencies. 

So far, this has been enough for Drill to query S3 via Jets3t, and Kinesis via Hive. It would be nice to only include the aws-java-sdk modules that a Drill user would actually use, along with their proper dependencies, resolving conflicts against what Drill already includes.

Below are my ideas for how this can be done:
* leverage https://github.com/awslabs/emr-bootstrap-actions/blob/master/gradle/install-gradle-bootstrap.sh to run gradle on each node
* provide a way for users to run gradle to resolve the classpath locally and upload the result to S3; since emr-* jars are not generally available, we can continue to add them as we are now
* maintain a curated classpath in this project, possibly generated by a maintainer running gradle locally, so that users need not have java installed locally in order to launch a cluster

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
