### ISSUE TITLE
Remove dependence on Impala for a robust Hive Metastore launcher

### ISSUE THREAD

**Issue by pmogren** [commercehub-oss/watershed#9]
Everything that's really needed seems to be preinstalled even when Impala is not selected. Maybe we can run a script to just stub out or comment out some things (missing Impala-specific directories and config files) to allow Impala's Hive Metastore script to work without Impala being selected. I think I did that by hand once. Ideally we could do this in a way that does not cause a conflict if the user does install Impala. 

Alternatively, we could probably copy and edit Impala's init script and remove Impala specifics. It would probably require some effort to be compatible with the user installing Impala, so more likely we'd try to detect that and do nothing, or force the user to declare that choice.

**Comment by pmogren** [comment]
Looks like a new EMR release doesn't provide Impala but does provide Hive Metastore.  https://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-release-components.html

**Comment by pmogren** [comment]
Impala itself (not Hive Metastore) is failing to start correctly, in an endless loop, logging all the while

**Comment by pmogren** [comment]
MapR 4.0 on EMR also relies on Impala to provide the Hive Metastore init script.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
